name: Generate Score Board

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-score-board:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "24"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: score

      - name: Run the JAR to generate file
        run: |
          java -jar playground/build/libs/playground-all.jar ./score/SCOREBOARD.md

      - name: Commit generated file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git merge main --no-edit
          git add score/SCOREBOARD.md
          git commit -m "Add score/SCOREBOARD.md from Github CI" || echo "No changes to commit"
          git push -f